/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {CodeQuality, CodeQualityMetrics, ComprehensiveAnalysis, ContributorStats, Feature, FileChange, FileSummary, ImpactAssessment, KnowledgeInsight, Link, References, Summary, TeamContribution, TeamProgress, TechnicalDebt, TechnicalImpact} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  CombineFileSummaries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): ComprehensiveAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "CombineFileSummaries",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ComprehensiveAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeFileChange(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): FileSummary {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeFileChange",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as FileSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  CombineFileSummaries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.ComprehensiveAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "CombineFileSummaries",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ComprehensiveAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeFileChange(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.FileSummary {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeFileChange",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.FileSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}