export interface ComponentData {
  id: string
  name: string
  description: string
  category: string
  preview?: string
  isPro?: boolean
  dependencies?: string[]
}

export interface ComponentCategory {
  id: string
  name: string
}

export const componentCategories: ComponentCategory[] = [
  { id: "layout", name: "Layout" },
  { id: "navigation", name: "Navigation" },
  { id: "inputs", name: "Inputs" },
  { id: "display", name: "Display" },
  { id: "feedback", name: "Feedback" },
  { id: "overlay", name: "Overlay" },
  { id: "data", name: "Data Display" },
  { id: "animation", name: "Animation" },
]

export const allComponents: ComponentData[] = [
  {
    id: "button",
    name: "Button",
    description: "A clickable button element with various styles and states.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Button",
  },
  {
    id: "card",
    name: "Card",
    description: "A container for content with a header, body, and footer.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Card",
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "A modal dialog that appears on top of the main content.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Dialog",
  },
  {
    id: "dropdown",
    name: "Dropdown",
    description: "A menu that appears when triggered by a button.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Dropdown",
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "A set of layered sections of content that display one at a time.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Tabs",
  },
  {
    id: "toast",
    name: "Toast",
    description: "A brief notification that appears temporarily.",
    category: "feedback",
    preview: "/placeholder.svg?height=200&width=300&text=Toast",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    description: "A small popup that appears when hovering over an element.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Tooltip",
  },
  {
    id: "avatar",
    name: "Avatar",
    description: "A graphical representation of a user or entity.",
    category: "display",
    preview: "/placeholder.svg?height=200&width=300&text=Avatar",
  },
  {
    id: "badge",
    name: "Badge",
    description: "A small count or status descriptor for UI elements.",
    category: "display",
    preview: "/placeholder.svg?height=200&width=300&text=Badge",
  },
  {
    id: "table",
    name: "Table",
    description: "A component for displaying tabular data.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=Table",
  },
  {
    id: "form",
    name: "Form",
    description: "A collection of form controls with validation.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Form",
  },
  {
    id: "input",
    name: "Input",
    description: "A form control for text input.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Input",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    description: "A form control for selecting multiple options.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Checkbox",
  },
  {
    id: "radio",
    name: "Radio",
    description: "A form control for selecting a single option from a group.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Radio",
  },
  {
    id: "select",
    name: "Select",
    description: "A form control for selecting from a list of options.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Select",
  },
  {
    id: "slider",
    name: "Slider",
    description: "A form control for selecting a value from a range.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Slider",
  },
  {
    id: "switch",
    name: "Switch",
    description: "A form control for toggling between two states.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Switch",
  },
  {
    id: "textarea",
    name: "Textarea",
    description: "A form control for multi-line text input.",
    category: "inputs",
    preview: "/placeholder.svg?height=200&width=300&text=Textarea",
  },
  {
    id: "alert",
    name: "Alert",
    description: "A component that displays a brief, important message.",
    category: "feedback",
    preview: "/placeholder.svg?height=200&width=300&text=Alert",
  },
  {
    id: "progress",
    name: "Progress",
    description: "A component that displays progress status for a task.",
    category: "feedback",
    preview: "/placeholder.svg?height=200&width=300&text=Progress",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    description: "A placeholder for content that is loading.",
    category: "feedback",
    preview: "/placeholder.svg?height=200&width=300&text=Skeleton",
  },
  {
    id: "spinner",
    name: "Spinner",
    description: "A loading indicator for asynchronous operations.",
    category: "feedback",
    preview: "/placeholder.svg?height=200&width=300&text=Spinner",
  },
  {
    id: "popover",
    name: "Popover",
    description: "A small overlay that appears on hover or click.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Popover",
  },
  {
    id: "drawer",
    name: "Drawer",
    description: "A panel that slides in from the edge of the screen.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Drawer",
  },
  {
    id: "accordion",
    name: "Accordion",
    description: "A vertically stacked set of interactive headings.",
    category: "display",
    preview: "/placeholder.svg?height=200&width=300&text=Accordion",
  },
  {
    id: "carousel",
    name: "Carousel",
    description: "A slideshow component for cycling through elements.",
    category: "display",
    preview: "/placeholder.svg?height=200&width=300&text=Carousel",
    isPro: true,
  },
  {
    id: "pagination",
    name: "Pagination",
    description: "A component for navigating between pages of content.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Pagination",
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    description: "A navigation component that shows the current location.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Breadcrumb",
  },
  {
    id: "menu",
    name: "Menu",
    description: "A list of options or commands.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Menu",
  },
  {
    id: "navbar",
    name: "Navbar",
    description: "A navigation bar that appears at the top of the page.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Navbar",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    description: "A navigation component that appears on the side of the page.",
    category: "navigation",
    preview: "/placeholder.svg?height=200&width=300&text=Sidebar",
  },
  {
    id: "footer",
    name: "Footer",
    description: "A component that appears at the bottom of the page.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Footer",
  },
  {
    id: "header",
    name: "Header",
    description: "A component that appears at the top of the page.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Header",
  },
  {
    id: "grid",
    name: "Grid",
    description: "A layout component for arranging content in a grid.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Grid",
  },
  {
    id: "container",
    name: "Container",
    description: "A layout component that centers content horizontally.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Container",
  },
  {
    id: "divider",
    name: "Divider",
    description: "A horizontal or vertical line that separates content.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Divider",
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    description: "A component that maintains a specific aspect ratio.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Aspect+Ratio",
  },
  {
    id: "data-table",
    name: "Data Table",
    description: "A component for displaying and interacting with tabular data.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=Data+Table",
    isPro: true,
  },
  {
    id: "calendar",
    name: "Calendar",
    description: "A component for displaying and selecting dates.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=Calendar",
    isPro: true,
  },
  {
    id: "chart",
    name: "Chart",
    description: "A component for visualizing data.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=Chart",
    isPro: true,
  },
  {
    id: "tree-view",
    name: "Tree View",
    description: "A component for displaying hierarchical data.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=Tree+View",
    isPro: true,
  },
  {
    id: "list",
    name: "List",
    description: "A component for displaying a list of items.",
    category: "data",
    preview: "/placeholder.svg?height=200&width=300&text=List",
  },
  {
    id: "hover-card",
    name: "Hover Card",
    description: "A card that appears when hovering over an element.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Hover+Card",
  },
  {
    id: "command",
    name: "Command",
    description: "A command palette for keyboard-first interactions.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Command",
    isPro: true,
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    description: "A custom scrollable area with custom scrollbars.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Scroll+Area",
  },
  {
    id: "separator",
    name: "Separator",
    description: "A horizontal or vertical line that separates content.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Separator",
  },
  {
    id: "sheet",
    name: "Sheet",
    description: "A dialog that slides in from the edge of the screen.",
    category: "overlay",
    preview: "/placeholder.svg?height=200&width=300&text=Sheet",
  },
  {
    id: "resizable",
    name: "Resizable",
    description: "A component that can be resized by the user.",
    category: "layout",
    preview: "/placeholder.svg?height=200&width=300&text=Resizable",
    isPro: true,
  },
  {
    id: "scroll-animation",
    name: "Scroll Animation",
    description: "Animations that trigger on scroll.",
    category: "animation",
    preview: "/placeholder.svg?height=200&width=300&text=Scroll+Animation",
    isPro: true,
  },
  {
    id: "hover-animation",
    name: "Hover Animation",
    description: "Animations that trigger on hover.",
    category: "animation",
    preview: "/placeholder.svg?height=200&width=300&text=Hover+Animation",
  },
  {
    id: "loading-animation",
    name: "Loading Animation",
    description: "Animations for loading states.",
    category: "animation",
    preview: "/placeholder.svg?height=200&width=300&text=Loading+Animation",
  },
  {
    id: "transition",
    name: "Transition",
    description: "Smooth transitions between UI states.",
    category: "animation",
    preview: "/placeholder.svg?height=200&width=300&text=Transition",
  },
  {
    id: "confetti",
    name: "Confetti",
    description: "A celebratory animation with confetti particles.",
    category: "animation",
    preview: "/placeholder.svg?height=200&width=300&text=Confetti",
    isPro: true,
  },
]

